### ISSUE TITLE
Error parsing empty component

### ISSUE THREAD

**Issue by aschempp** [cyon/vue-translation-manager#9]
If a file does not have any translations, the CLI tool will terminate with an error:

```
(node:31777) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by MaxGfeller** [comment]
@aschempp How can this be recreated? The CLI tool should not even show components that don't have any strings in them to be translated.

**Comment by MaxGfeller** [comment]
I fixed a bug in `1.1.0` that lead to the same error message. Could you try again and check if it works now?

**Comment by aschempp** [comment]
I tried removing everything except the div and export statement, and the error still comes up.

**Comment by MaxGfeller** [comment]
I'm failing to recreate this. Could the error actually be from your messages file(s)? Sorry the error handling is still very basic.

When does the error occur? Right after running `translate` or only after selecting a file?

**Comment by aschempp** [comment]
After selecting that file. Other files work just fine. All languages are stored in the same file. Here's what my config looks like:

```js
const path = require('path');
const { JSONAdapter } = require('vue-translation-manager');

module.exports = {
    srcPath: path.join(__dirname, 'src/components/'),
    adapter: new JSONAdapter({ path: path.join(__dirname, 'src/i18n/messages.json')}),
    languages: ['en', 'de'],
};
```

**Comment by MaxGfeller** [comment]
I can not recreate this, still. Is the messages file valid JSON? Did you try to validate this?

Could you provide a small reproducable example so i could look into this?

**Comment by qzminski** [comment]
I can confirm the issue but I am not sure what's the source of the problem…

**Comment by the94air** [comment]
@MaxGfeller Turns out it shows this error if any of your templates contains an `&` :joy:
